config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do 
      match  :vieworder, :via =>[:get, :post]
    end
  end
  root 'orders#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]


  def vieworder
    resp = JSON.parse(params[:JSONData])
    result = JSON.parse(resp['Result'])
    ap result
  end
  # MerchantID = '11940506'
  # HashKey = '9npBbx2Y38q1sFA70jWezAS4OeCVCLBM'
  # HashIV ='80okyqiBzJC1od9p'
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show 
  	
  	@MerchantID = '11940506'
  	@HashKey = '9npBbx2Y38q1sFA70jWezAS4OeCVCLBM'
  	@HashIV ='80okyqiBzJC1od9p'
  	#set_order #@order = Order.find(params[:id])
  	# 智付寶文件規定的5個欄位必須按照字母順序

	chain = "Amt=#{@order.total}&MerchantID=#{@MerchantID}&MerchantOrderNo=#{@order.id}&TimeStamp=#{@order.created_at.to_i}&Version=1.2"

	# 頭先加上 HashKey，尾再加上 HashIV ，最後以 SHA-256 加密後再轉大寫
	@check_value = Digest::SHA256.hexdigest("HashKey=#{@HashKey}&#{chain}&HashIV=#{@HashIV}").upcase
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pay2goTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" href=""> -->
      <%= link_to "智付寶刷卡測試", root_path, :class => "navbar-brand" %> 
        <!-- <img alt="Brand" src="..."> -->
       
  
       <a class="navbar-brand" href="https://www.pay2go.com/dw_files/info_api/pay2go_gateway_MPGapi_V1_1_7.pdf">
        
       官方文件 
      </a>

      <a class="navbar-brand" href="http://fifiteen82726-blog.logdown.com/posts/734567-rails-think-tank-fubaojin-flow">
        
       教學BLog 
      </a>
    </div>
  </div>
</nav>

<%= yield %>

</div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>


<%= image_tag("pay2go.jpg") %>

<%= link_to 'New Order', new_order_path %>

<div class="col-md-12">
  <div class="col-md-6">
    <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Price</th>
        <th>Pay</th>
      </tr>
    </thead>

  <tbody>
    <% @orders.each do |order| %>
    
      <tr>
        <td><%= order.id %></td>
        <td><%= order.total %></td>
    
        <td><%= link_to 'Pay', order %></td>
      </tr>
    <% end %>

  </tbody>
</table>
  </div>
</div>


<br>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<%= @order.total %>



<form method="post" action="https://capi.pay2go.com/MPG/mpg_gateway">               <!-- 此為測試的 url, 正式為 : https://api.pay2go.com/MPG/mpg_gateway -->
  <input type="hidden" name="MerchantID" value="<%= @MerchantID %>"/>
  <input type="hidden" name="RespondType" value="JSON"/>
  <input type="hidden" name="CheckValue" value="<%= @check_value %>"/>
  <input type="hidden" name="TimeStamp" value="<%= @order.created_at.to_i %>"/>
  <input type="hidden" name="Version" value="1.2"/>
  <input type="hidden" name="MerchantOrderNo" value="<%= @order.id %>"/>
  <input type="hidden" name="Amt" value="<%= @order.total %>"/>
  <input type="hidden" name="ItemDesc" value="TESTTESTTEST"/>                       <!-- 商品資訊，先隨便帶 -->

  <!-- 回傳的url -->
  <!-- <input type="text" name="CustomerURL" value="<%= vieworder_orders_url%>"/> -->
  <input type="hidden" name="Email" value="fifiteen82726@gmail.com"/>        
  <!-- 付款成功時會依照 Email 欄位填的 Email 寄送付款成功信件 -->
  <input type="hidden" name="LoginType" value="0"/>    
  <input type="hidden" name="ReturnURL" value="<%= vieworder_orders_url%>"/>    


  <!-- 0 = 不須登入智付寶會員 -->
  <button type="submit">付款</button>
</form>



<%#= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/vieworder.html.erb
I am return url



吐回來的東西 
<!-- 

{"JSONData"=>"{\"Status\":\"SUCCESS\",
\"Message\":\"\\u6388\\u6b0a\\u6210\\u529f\",
\"Result\":\"{\\\"MerchantID\\\":\\\"11940506\\\",
\\\"Amt\\\":100,
\\\"TradeNo\\\":\\\"16052720552324515\\\",
\\\"MerchantOrderNo\\\":\\\"4\\\",
\\\"RespondType\\\":\\\"JSON\\\",
\\\"CheckCode\\\":\\\"15ACD5044D4E7D549C084A1BDCD99CF190D929CC18E5D100B248949CA3CEB516\\\",
\\\"IP\\\":\\\"27.245.30.64\\\",
\\\"EscrowBank\\\":\\\"KGI\\\",
\\\"ItemDesc\\\":\\\"TESTTESTTEST\\\",
\\\"IsLogin\\\":true,
\\\"PaymentType\\\":\\\"CREDIT\\\",
\\\"PayTime\\\":\\\"2016-05-27 20:55:23\\\",
\\\"RespondCode\\\":\\\"00\\\",
\\\"Auth\\\":\\\"930637\\\",
\\\"Card6No\\\":\\\"400022\\\",
\\\"Card4No\\\":\\\"2222\\\",
\\\"Exp\\\":\\\"2102\\\",
\\\"TokenUseStatus\\\":0,
\\\"InstFirst\\\":100,
\\\"InstEach\\\":0,
\\\"Inst\\\":0,
\\\"ECI\\\":\\\"\\\"}\"}"} -->